server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

camunda:
  bpm:
    database:
      schema-update: true
    auto-deployment-enabled: true
    filter:
      create: All tasks
    webapp:
      enabled: true
    admin-user:
      id: demo
      password: demo
      firstName: Demo
    xml:
      enable-safe-xml: false
    # ADD THESE TWO LINES TO DISABLE DTD PROCESSING
    parser:
      process-validation-external-entity-resolution-disabled: true
      process-validation-dtd-validation-disabled: true